### ISSUE TITLE
Enhance folding for node groups defined with numerical factorization

### ISSUE THREAD

**Issue by kcgthb** [cea-hpc/clustershell#228]
When a group is defined with some numerical factorization (eg. node123[1-2]), regrouping doesn't recognize the original group:

#### nodeset definition
```
$ nodeset -ll @test
@test node123[1-2]
```

#### folding works 
```
$ nodeset -f $(nodeset -e @test)
node[1231-1232]
```

#### folding using groups doesn't recognize the group definition
```
$ nodeset -r $(nodeset -e @test)
node[1231-1232]
```

#### expected result
```
$ nodeset -r $(nodeset -e @test)
@test
```
```
$ nodeset --version
nodeset 1.6
```

**Comment by thiell** [comment]
Hi kcgthb,
We are going to land a first patch for 1.7 that explicitly reject such nodeset construction for now, as it has some dangerous consequences like this (-i is intersection):
```bash
 $ echo node1231 | nodeset -f -i node[1231-1232]
 node1231
 $ echo node1232 | nodeset -f -i node123[1-2]

 $
```
Indeed the current parser builds string patterns based on present digits and ranges but is not able to aggregate them if they are contiguous. Constructions like `node[1-2]34` were already rejected. In some cases like yours and the one below, if not rejected, it can lead to wrong operations because clustershell thinks the patterns are different. This is not acceptable and our priority.

A future fix will be to enhance the parser and make it capable of merging ranges with prefixed/suffixed digits.

**Comment by thiell** [comment]
Increasing priority as it's becoming a real issue/regression as this kind of construction is often found in some well-known cluster vendor documentation and is really useful for large 0-padded nodeset. We should at least support this kind of construction: `prod-00[01-32]`.

**Comment by thiell** [comment]
https://review.gerrithub.io/#/c/250058/

showcase:

```console
$ nodeset -f prod-00[1-2]0
prod-[0010-0020]
```

use-case mentioned above now works as expected:
```console
$ echo node1231 | nodeset -f -i node[1231-1232]
node1231
$ echo node1232 | nodeset -f -i node123[1-2]
node1232
```

Everything works except tricky cases:

* padding mismatch:

```console
$ nodeset -f prod-02[10-34,069-099]
prod-[0210-0234,2069-2099]
```

* trailing digits w/ step syntax

```console
$ nodeset -f prod-02[1-9/2]
prod-[021,023,025,027,029]
$ nodeset -f prod-02[1-9/2]0
nodeset: Parse error: illegal trailing digits after range with steps: "0"
```
