### ISSUE TITLE
ssh vs. paramiko

### ISSUE THREAD

**Issue by brianjmurrell** [cea-hpc/clustershell#253]
Just curious about your thoughts on calling out to the ```ssh``` binary vs. using something like [Paramiko](http://www.paramiko.org/).

**Comment by thiell** [comment]
Hi Brian,

Actually, we did some tests some years ago and Paramiko was way too slow compared to forking `ssh` binary. IIRC its implementation is in pure Python and couldn't beat a ssh C implementation (even with the forking overhead). The other issue we had at this time was that Paramiko couldn't use regular OpenSSH configuration files. We wanted clustershell (and tools like clush) to be straightforward to install, and cluster often (always?) have customized ssh_config/sshd_config.

I didn't have a look at Paramiko recently, so if you know that some of these limitations are now out of date, please let us know.

As clustershell forks a bunch of ssh, at that time we primarily focused on `subprocess.Popen`, which was serializing parallel forks. That's why clustershell comes with `ClusterShell.Worker.fastsubprocess` that removes this Python limitation (they have some good reasons to keep subprocess as is).

**Comment by degremont** [comment]
> We wanted clustershell (and tools like clush) to be straightforward to install, and clusters often (always?) have customized ssh_config/sshd_config.

This is something really important IMHO.
Moreover, paramiko, performances aside, is lacking a lot of SSH features. And I see no point in using something that is always trying to cope with that, running behind ssh and that will never catch it.

Actually, I see not "Pros" paramiko for clustershell, only "Cons".

ClusterShell is using "workers" as backend for real connections. ssh is only one of them. We supports others. Somebody could try a proof-of-concept of a ParamikoWorker. But as CS is really fork-oriented, this could be raised some funny issues :)

**Comment by brianjmurrell** [comment]
Fair enough points.  I just wondered if you had considered Paramiko and what your reasons for not using it were.
