### ISSUE TITLE
Gracefully supports offline gateways

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#260]
If one host is down, in a group of gateway managing a group of nodes, this should not prevent commands from reaching the target nodes. Messages should be automatically distribute across other usable gateways.

**Comment by thiell** [comment]
Also - it is probably linked - if a gateway host name doesn't resolve, clush gets blocked despite the clear error at start.

**Comment by degremont** [comment]
+1 on this issue.

We are facing this problem with simply offline gateways. No need for a failover system, just `ev_close()` clearly called and error raised to CLIs.

**Comment by kcgthb** [comment]
That would be useful for us too. We have a use case where multiple gateways are possible to reach nodes, although some are preferred because they provide a more direct path. Yet, when they're offline, falling back to a less preferred gateway would be necessary. 
Generalizing the concept with weighted gateways (as proposed in #374) sounds like the perfect plan!

**Comment by degremont** [comment]
For us the big problem right now is the silent failure and, as no event is triggered, everything is stuck (like `clush`). 3 steps?
1. raise error when gateway is unreachable
2. fail over another gateway if possible when the first one is unreachable
3. pick gateways if the preferred order
