### ISSUE TITLE
clush -b doesn't handle % in node names

### ISSUE THREAD

**Issue by martinetd** [cea-hpc/clustershell#275]
Example:

    $ clush -bw fe80::5054:ff:feff:6944%eth0 echo ok
    clush: Parse error: Internal error: node pattern and ranges mismatch : "fe%s::%s:ff:feff:%s%eth%s"

**Comment by degremont** [comment]
Bug comes from ```GatherOutputHandler.ev_close()```

It uses  ```NodeSet._fromlist1( ... )``` to parse pattern. This method uses ```ParsingEngine.parse_string_single()``` which do not apply ```%``` protection, because it directly calls ```_scan_string_single()```. Only ```_scan_string()``` do the job correctly. 

Need to consider if this is correct and relevant to call ```_scan_string_single()``` outside of ```scan_string()```

**Comment by thiell** [comment]
Thanks much for reporting, that nodeset is so pretty... ;)

First of all, I have just verified that _fromlist1 is still useful in term of performance. Feel free to try this for example: https://gist.github.com/thiell/9ae3ad45f7563e95d034

As a reminder, `NodeSet._fromlist1` is a private optimized constructor that takes a list of single-node string.

`ParsingEngine.parse_string_single()` is only used by `NodeSet._fromlist1` for this case, and call `_scan_string_single()` which doesn't escape %, as this one is already called by `_scan_string`. I propose the following changes in an upcoming patch to clean up things:
* remove pre-escaping from `_scan_string`, so that no escaping is performed in `_scan_*` methods
* % escaping has to be performed by calling function, like `parse_string_single` or `parse_string`

The patch is ready, I just need to write some tests for it. It should pop up in gerrit soon :)

**Comment by thiell** [comment]
Now, I am so glad we didn't choose to use % as a special operator!
