### ISSUE TITLE
ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by ChristianKniep** [cea-hpc/clustershell#285]
Bonjour a tous,

I like to use clustershell on my Macbook (El Capitan), but I get this error... :(

```
clush -w docker1 uptime
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 745, in clush_excepthook
    raise exp
ValueError: current limit exceeds maximum limit

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/clush", line 10, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 890, in main
    set_fdlimit(config.fd_max, display)
  File "/usr/local/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 724, in set_fdlimit
    resource.setrlimit(resource.RLIMIT_NOFILE, (rlim_max, hard))
ValueError: current limit exceeds maximum limit
```
I assume it something simple but google failed me so far.

**Comment by degremont** [comment]
clush try to maximize the parallelism. For that, it needs to open a lot of file descriptor. This can be controlled with ```fd_max``` (see ```man clush.conf```)

The value in ```clush.conf``` is probably higher than the permitted value on your system.
See:

```
 ulimit -n
 ulimit -n -H
 grep fd_max /etc/clustershell/clush.conf ~/.clush.conf
```

**Comment by ChristianKniep** [comment]
That was fast... Thanks, I just created `~/.clush.conf`.

**Comment by ChristianKniep** [comment]
```
cat ~/.clush.conf
[Main]
fanout: 128
connect_timeout: 15
command_timeout: 0
history_size: 100
color: auto
fd_max: 2500
```

**Comment by degremont** [comment]
Maybe we should keep this ticket open to track this uncatched exception. Should be better to catch it and display a better error message...

**Comment by thiell** [comment]
I will take a look, we should indeed improve the error message.

**Comment by thiell** [comment]
The default `fd_max` in /etc/clustershell/clush.conf is **16384**.

On Mac OS X, ulimit says that the hard limit is unlimited, but the kernel limit takes precedence (of course):

```console
$ ulimit -n -H
unlimited
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 10240
```

That is why clustershell isn't able to raise it to 16384 (default soft limit is 256).

The problem is that _python setup.py install_ out of the box on Mac OS X doesn't work right now, just because of this.... The user has to change it in `/etc/clustershell/clush.conf` (or locally in `~/.config/clustershell/clush.conf` or `~/.clush.conf` as did @ChristianKniep).

If a lot of FDs is really needed, the hard limit might be raised that way (not permanent):
```console
$ sudo sysctl -w kern.maxfilesperproc=20000
kern.maxfilesperproc: 10240 -> 20000
```

We could decrease the default fd_max value to 10240 or even 8192 (should be enough for most sites !). @degremont: What do you think?

In any case, I will fix the error message!

**Comment by degremont** [comment]
IIRC, we need 3 fds per EngineClient, that means 8192 will be fine for any fanout below 2730? If correct, I'm fine with decreasing the default value to 8192

**Comment by shm007g** [comment]
sudo launchctl limit maxfiles 65536 200000
