### ISSUE TITLE
More explanation for tree mode: fanout, -o

### ISSUE THREAD

**Issue by degremont** [cea-hpc/clustershell#317]
Tree mode introduces a lot of "blurry" behaviour and it is difficult for users to understand what is the current behaviour for a couple of options. This should be clarify and documented:

Could you tell me easily, what is the behaviour, in tree mode of this option:

* ``--option``? Is this for gateway, for final connections to the nodes, both?
* ``fanout``? global or per gateway? If you hit ``Enter`` during a clush command, ouput is ... strange and does not help users understand what is the current behaviour.

I assume there are more of these.

Regarding fanout, ``clush --fanout=1`` is broken...

**Comment by degremont** [comment]
* ``fanout=1`` issue will be solved by another ticket.
* For now, I think we should just add explanation in documentation and man pages to simply explain that fanout value (from config or overriden by CLI option) will be copied on every gateway. With an example. 
* The strange output should be verified with the fanout fix to verify things are clearer.

**Comment by thiell** [comment]
* `fanout=1` has been fixed in #322
* `-o` or `-O` options propagation needs a fix (see https://review.gerrithub.io/#/c/298393/)
* **fd_max** is a specific case that could be handled in 1.8 (see #325)
* options and fanout in tree mode documentation improvements @ https://review.gerrithub.io/#/c/298394/
