### ISSUE TITLE
Update licensing to CeCILL v2.1 (and/or a more mainstream license)

### ISSUE THREAD

**Issue by paravoid** [cea-hpc/clustershell#321]
We, here at the Wikimedia Foundation, are interested in using ClusterShell for our servers. However, we have a very strict "only open-source tools" policy and thus we would like to make sure that ClusterShell is under a suitably free/open-source license before we start relying on it.

I noticed that ClusterShell is licensed under a bit of a niche license, the CeCILL. Moreover, it looks like it's licensed under CeCILL v1.0; however, according to CeCILL's homepage, v2.1 was the first version approved by the OSI (and is thus the first version of CeCILL that is actually considered an open-source license officially).

It would nice if ClusterShell would *at least* upgrade to the CeCILL v2.1. In my opinion, it would be even better if the software was switched (or dual-licenced) using a more mainstream/popular (and tested in court!) license, such as the (L)GPLs, but I realize there might be external, mitigating factors for this choice.

**Comment by thiell** [comment]
Hi @paravoid. I am very glad that the Wikimedia Foundation is interested in ClusterShell. It has been a while since we want to change the license to a more popular license as you said. Your ticket is a good opportunity for us to try making that change now, and I want to thank you for that.

The proposal is to switch to the OSI-approved license "LGPL v2.1 or later" (which is very close to the CeCILL-C v1 that we currently use).

I will send an email to each ClusterShell contributor so they can acknowledge the change in this ticket. If we succeed, I will create a commit in gerrithub that will have to be Signed-off by all current contributors. They are (only) 7 contributors.

**Comment by degremont** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by getreu** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by rezib** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by martinetd** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by bougetq** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by degremont** [comment]
@paravoid, may I ask what part of ClusterShell do you plan to use?

**Comment by hdoreau** [comment]
I agree to change the license to “LGPL v2.1 or later”.

**Comment by volans-** [comment]
@degremont, we are planning to use it mostly as a library for parallel remote execution in a custom framework.

**Comment by paravoid** [comment]
Thank you *so much* everyone!
