### ISSUE TITLE
Is there anyway to stop all remote commands ?

### ISSUE THREAD

**Issue by patlucas** [cea-hpc/clustershell#396]
task.abort, due to behaviour of ssh, doesn't kill remote running command. Is there anyway to kill running remote commands or propagate a signal to them (a trapped sigint as example ...) ?

**Comment by thiell** [comment]
Hey @patlucas! Excellent question. But I don't think there is a way to do it because of ssh. We would need to track remote command PIDs and (correct me if I'm wrong) ssh doesn't offer this possibility.

**Comment by degremont** [comment]
Propagating signal through SSH tunnel was just added in one the latest SSHd release.

If you (likely) do not use this version, you have to manage it yourself by hand.

**Comment by patlucas** [comment]
Many thanks for your responsive and valuable comments ! We only have to wait for an update of sshd, meanwhile we simply add a distributed "pkill" action to our script.

**Comment by brianjmurrell** [comment]
Any progress on this given that it's now almost 4 years later?

**Comment by thiell** [comment]
Hi @brianjmurrell!

I closed this issue because I didn't think there was anything we could do on our side. But thanks for bringing this again, so we know it is still a problem. I've done some more research and I don't think I am ready to re-open this issue yet, unless we want to go with the pseudo tty route, or need to add support for ssh client alternatives

`ssh -t` (or `-tt` to force) sets up a pseudo tty between the source and destination, which indeed seems to propagate signals and even generates a SIGHUP signal to the command when the ssh connection is lost. But we generally don't want to use pseudo ttys with `clush`, because tty is for interactive use, comes with added complexity and I noticed that it does mess up stdin propagation handling (currently using `ssh -tt` with `clush` breaks `echo foo | clush -w dest cat` for example). But if you add `ssh_options: -tt` to `clush.conf`, then running a simple `sleep` command will be killed when `clush` is aborted.

In general, we want no tty to be used with `clush` (the parent process of the command should be `sshd: root@notty` on the destination node in that case). Still, we would like to propagate a signal to our command, ideally via the existing ssh connection. When using `clush` with `ssh`, `clush` itself does not run on the target nodes, we rely on ssh/sshd for remote command execution.

Now, the SSH 2 protocol documents a signal delivery mechanism, see [RFC 4254 6.9](https://www.rfc-editor.org/rfc/rfc4254#section-6.9). However, it is actually a relatively recent (2018) addition in OpenSSH server. For the related ticket, see: https://bugzilla.mindrot.org/show_bug.cgi?id=1424
Server-side signal handling is available starting with OpenSSH server 7.9. See [openssh 7.9 release notes](https://www.openssh.com/txt/release-7.9) "sshd(8): support signalling sessions via the SSH protocol."

That's a great step forward, but unfortunately.. that is not enough, because it doesn't seem to be possible to send a signal over an existing ssh session using the OpenSSH client at this time. There is one [openssh client patch available](https://bugzilla.mindrot.org/attachment.cgi?id=1699), that proposes to add support for signal/kill from the ssh client and also an escape sequence `+  %cS  - Send a signal (SSH protocol 2 only)\r\n\`. Now, other SSH clients might implement a similar feature already (like [AsyncSSH](https://asyncssh.readthedocs.io/) mentioned in the ticket, but I haven't looked at any of them. Depending on how this is implemented on the ssh client side, we might have to add some special support in ClusterShell, or perhaps this could just be a matter of setting the option in `clush.conf` via `ssh_options:`.

Note: There also _may_ be ways to find workarounds with `clush` when using the tree mode with [--remote=no](https://clustershell.readthedocs.io/en/latest/tools/clush.html#tree-mode-specific-options).
